/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BilibiliGrid: typeof import('./components/BilibiliGrid.vue')['default']
    DateNavigator: typeof import('./components/DateNavigator.vue')['default']
    DayView: typeof import('./components/DayView.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    PlatformTabs: typeof import('./components/PlatformTabs.vue')['default']
    SearchPanel: typeof import('./components/SearchPanel.vue')['default']
    SearchResultItem: typeof import('./components/SearchResultItem.vue')['default']
    SnapshotCard: typeof import('./components/SnapshotCard.vue')['default']
    SnapshotTimeline: typeof import('./components/SnapshotTimeline.vue')['default']
    TrendChart: typeof import('./components/TrendChart.vue')['default']
  }
}
