name: fetcher-weibo-hot-search

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-weibo-hot-search:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        working-directory: "./Fetchers/CN/"
        run: |
          python -m pip install --upgrade pip

          pip install selenium pandas bs4 lxml

          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          }

      - uses: browser-actions/setup-chrome@v1

      - name: Run fetcher
        working-directory: "./Fetchers/CN/"
        run: |
          python ./fetcher-weibo-hot-search.py

      - name: Commit report
        run: |
          git config --global user.name 'Dynesshely'
          git config --global user.email 'catrol@qq.com'
          git add .
          git stash
          git checkout -b fetch=weibo-hot-search
          git stash pop
          git commit -am "fetched from '微博热搜'"
          git push -u origin fetch=weibo-hot-search
