name: fetcher-weibo-hot-search

on:
  schedule:
    - cron: "0 18,4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-weibo-hot-search:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@v1

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: "./Fetchers/CN/"
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas bs4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run fetcher
        working-directory: "./Fetchers/CN/"
        run: |
          python ./fetcher-weibo-hot-search.py

      - name: Commit report
        run: |
          git config --global user.name 'Dynesshely'
          git config --global user.email 'catrol@qq.com'
          git add .
          git commit -am "📄 Docs: Fetched from '百度热搜'."
          git push
