name: launcher-cn

on:
  schedule:
    - cron: "0 18,4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-baidu-hot-search:
    uses: ./.github/workflows/fetcher-baidu-hot-search.yml

  fetch-bilibili-hot-videos:
    uses: ./.github/workflows/fetcher-bilibili-hot-videos.yml

  fetch-weibo-hot-search:
    uses: ./.github/workflows/fetcher-weibo-hot-search.yml

  merge:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - fetch-baidu-hot-search
      - fetch-bilibili-hot-videos
      - fetch-weibo-hot-search

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - shell: pwsh
        run: |
          git config --global user.name 'Dynesshely'
          git config --global user.email 'catrol@qq.com'
          git checkout main

          $branches = (
            'fetch=baidu-hot-search',
            'fetch=bilibili-hot-videos',
            'fetch=weibo-hot-search'
          )

          $branches | ForEach-Object {
            git merge $_ main
          }

          git push origin main
